services:
  dockterminal:
    image: dockterminal:latest
    build: .
    container_name: dockterminal
    restart: unless-stopped
    ports:
      - "5001:5001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/stacks:/opt/stacks
    environment:
      - DOCKTERMINAL_STACKS_DIR=/opt/stacks
